name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter:
    sdk: flutter


flutter:


  uses-material-design: true

